name: Check for Star

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  check-star:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user starred the repo
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const username = context.payload.sender.login;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Skip if author is the repo owner
            if (username === owner) return;

            try {
              // Check if user has starred the repo
              await github.rest.activity.checkRepoIsStarredByUser({
                username,
                owner,
                repo
              });
              console.log(`${username} has already starred the repo.`);
            } catch (error) {
              if (error.status === 404) {
                const issue_number = context.payload.issue?.number || context.payload.comment?.issue_url.split('/').pop();

                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number,
                  body: `👋 Hey @${username}, glad you're using Foblex Flow!
                          If the library has helped you — consider supporting the project with a star on GitHub. It really helps with visibility and further development 🌟
                          👉 https://github.com/${owner}/${repo}`
                });
              } else {
                throw error;
              }
            }
